name = "seaofclouds"
main = "dist/_worker.js"
compatibility_date = "2025-08-22"

# Default configuration (for local dev)
[vars]
ALLOWED_ORIGINS = "http://localhost:8787"
ENVIRONMENT = "development"

# R2 bucket for asset storage (local dev - no KV)
[[r2_buckets]]
binding = "R2_STORAGE"
bucket_name = "seaofclouds-assets"

# Optional cron triggers (commented out for now)
# [triggers]
# crons = ["*/15 * * * *"]

# Production environment (seaofclouds-production worker)
[env.production]
vars = { ALLOWED_ORIGINS = "https://dev.seaofclouds.com,https://www.seaofclouds.com,https://seaofclouds.com", ENVIRONMENT = "production" }
route = { pattern = "dev.seaofclouds.com", custom_domain = true }

[[env.production.kv_namespaces]]
binding = "ADOBE_LIGHTROOM_TOKENS"
id = "80b8f7971b01450a95bd96b75f9caa86"

[[env.production.kv_namespaces]]
binding = "ADOBE_OAUTH_TOKENS"
id = "b4606e3118c94b25a0b99ff9815fc8ca"

[[env.production.kv_namespaces]]
binding = "RATE_LIMITS"
id = "5258468969ef40ab9ba1252d0c764f2d"

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "5258468969ef40ab9ba1252d0c764f2d"

[[env.production.r2_buckets]]
binding = "R2_STORAGE"
bucket_name = "seaofclouds-assets"

# Development environment override
[env.development]
vars = { ALLOWED_ORIGINS = "http://localhost:8787", ENVIRONMENT = "development" }
# Development uses no KV namespaces or R2 buckets - will use local storage